prompts:
  - "A DJ in vibrant Nigerian attire stands behind a mixing console, adjusting knobs with focused precision."
  - "He glances at the audio waveforms on his monitor, syncing his movements to the rhythm of the track."
  - "With smooth hand gestures, he manipulates the turntables, blending beats seamlessly in the studio."
  - "The DJ nods along to the music, fully immersed as he fine-tunes levels and effects."
  - "His reflection is visible in the glass window as he dances subtly while mixing."
  - "He lifts one hand in the air, hyping the unseen audience as the bass drops."